package testquestion;

public class maxprofit_main {

	public static void main(String[] args)  {
		// TODO Auto-generated method stub
		// calling the function 
		// fist i creating the constructor then 
		maxprofit shivam  = new maxprofit("shivam singh ");
	// now test the calling the static function 
		 // successfully call the maxprofit function 
	shivam.setSaller_name("shivam");
	// creating the printing function for that object 
	shivam.printseller_name();
	// creating the array 
	int[]arr = {30 ,20 ,53 ,14} ; 

	
	System.out.println();
	
	shivam.setArr(arr);
	try {
		shivam.printarray();
	} catch (Exception e) {
		// TODO Auto-generated catch block
		System.out.println("this is the null pointer exception ");
	}
//	shivam.quickshorts(arr, 0, arr.length-1);
  //   shivam.quick();
	shivam.quick();
	System.out.println();
	try {
		shivam.printarray();
	} catch (Exception e) {
		// TODO Auto-generated catch block
		System.out.println("this is the null pointer exception ");
	}
	
	
	maxprofit itisha = new maxprofit("itisha singh ") ; 
	// now  checking the printing the variable 
	System.out.println();
	System.out.println(itisha.getArr());
	try {
		itisha.printarray();
	} catch (Exception e) {
		// TODO Auto-generated catch block
		System.out.println("this is the itisha object exception that is  generated by when you enter null ");
	}
	
	// calling the function of the maxprofit 
	shivam.maxprofit();
	System.out.println(shivam.getTotal_profit());
	System.out.println(shivam.getSeller_priese());
	
	shivam.printOverAllValue();
	itisha.printOverAllValue();
	}

}
